"""Uni-Lab-OS 设备大类标准模板集。"""

from . import peristaltic_pump  # noqa: F401  (蠕动泵)
from . import syringe_pump  # noqa: F401  (注射泵)
from . import multiway_valve  # noqa: F401  (多通阀)
from . import refrigerated_centrifuge  # noqa: F401  (低温或冷冻离心机)
from . import rotary_evaporator  # noqa: F401  (旋转蒸发器)
from . import preparative_chromatograph  # noqa: F401  (制备色谱仪)
from . import temperature_controlled_magnetic_stirrer  # noqa: F401  (控温磁力搅拌器)
from . import photochemical_reactor  # noqa: F401  (光化学反应器)
from . import refrigerator  # noqa: F401  (冷藏箱)
from . import freezer  # noqa: F401  (冷冻箱)
from . import fridge_freezer  # noqa: F401  (冷冻冷藏箱)
from . import low_temp_freezer  # noqa: F401  (低温冰箱)
from . import ultra_low_temp_freezer  # noqa: F401  (超低温冰箱)
from . import deep_low_temp_freezer  # noqa: F401  (深低温冰箱)
from . import blood_bank_refrigerator  # noqa: F401  (血液柜)
from . import pharmacy_refrigerator  # noqa: F401  (药品柜)
from . import vaccine_refrigerator  # noqa: F401  (疫苗柜)
from . import food_refrigerator  # noqa: F401  (食品柜)
